#cloud-config
users:
  - name: opam
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: opam
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA09mqKPpMJ4tyOpl4l+KTTl1DqjFT2mRD29HW8VwnmB root@alpha
runcmd:
  - echo "AcceptEnv=*" > /etc/ssh/sshd_config.d/acceptenv.conf
  - curl -L https://github.com/ocaml/opam/releases/download/2.2.1/opam-2.2.1-x86_64-linux -o /usr/bin/opam
  - chmod +x /usr/bin/opam
  - apt install build-essential unzip bubblewrap -y
  - su - opam -c "git clone https://github.com/ocaml/opam-repository"
  - su - opam -c "opam init -k local -a /home/opam/opam-repository --bare"
  - su - opam -c "rm -rf .opam/repo/default/.git"
  - su - opam -c "echo export OPAMYES=1 OPAMCONFIRMLEVEL=unsafe-yes OPAMERRLOGLEN=0 OPAMPRECISETRACKING=1 >> .profile"
  - su - opam -c "opam switch create 4.14 --packages=ocaml-base-compiler.4.14.2"
  - su - opam -c "opam pin add -k version ocaml-base-compiler 4.14.2"
  - su - opam -c "opam install -y opam-depext"
  - poweroff
